### ISSUE TITLE
ESM import example in README.md fails

### ISSUE THREAD

**Issue by rudikershaw** [matteobad/vanilla-fade#50]
Hi there,

Thought I ought to let you know that the examples you describe in your README.md for importing submodules are failing.
```
// ESM
import 'vanilla-fade/esm'; // all the library
import 'vanilla-fade/esm/fadeIn'; // single animation
import 'vanilla-fade/esm/fadeOut'; // single animation
import 'vanilla-fade/esm/fadeToggle'; // single animation
import 'vanilla-fade/esm/fadeTo'; // single animation
```
Getting it working in my project was as simple as adding the "dist" directory to the import statement.
```
import 'vanilla-fade/dist/esm/fadeOut';
```

**Comment by matteobad** [comment]
@rudikershaw, thank you for your feedback, I'm going to merge your PR right away. 😁
